config/routes.rb
Rails.application.routes.draw do
  get 'canzones/new'
  get 'canzones/create'
  get 'canzones/destroy'
  get '/' => 'songgoers#show'
  post '/login' => 'sessions#create'
  get '/login' => 'songgoers#show' 
  resources :songs
  post '/logout' => 'sessions#destroy'
  resources :song do
   resource :canzones, only: [:new,:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canzone.rb
class Canzone<ActiveRecord::Base
  belongs_to :song
  belongs_to :songgoer
end

app/models/song.rb
class Song < ApplicationRecord
	has_many :lyrics
	has_many :canzones
end

app/models/songgoer.rb
class Songgoer < ApplicationRecord
	has_many :lyrics
	has_many :canzones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :check_user_logged_in
	
	def check_user_logged_in
	    if session[:user]==nil then
	    	redirect_to login_path
	    end
	end
end

app/controllers/canzones_controller.rb
class CanzonesController < ApplicationController

  def new
  
  end

  def create
  	id_song = params[:song_id]
  	user_id = session[:user_id]
  	@song = Song.find(id_song)
  	@canzone = @song.canzones.create!(:testos => params[:canzone][:testos],:songgoer_id => user_id)
  	redirect_to songs_path 
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :check_user_logged_in
    def create
        name = params[:user][:name]
        password =params[:user][:password]
        @current_user = Songgoer.where(:name=> name)
        if @current_user.length==0 or
           @current_user[0][:password]!=password
        then
            flash[:loginerror]=true
            redirect_to login_path
        else
            #@current_user[0][:id]
            session[:user]=@current_user[0][:name]
            session[:user_id]=@current_user[0][:id]
            redirect_to songs_path
        end
    end
    
    def destroy
    	session.delete(:user)
    	redirect_to login_path    
    end
end

app/controllers/songgoers_controller.rb
class SonggoersController < ApplicationController
        skip_before_action :check_user_logged_in
        def show
        end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	skip_before_action :verify_authenticity_token
	
	def index
		@all = Song.all
		#render json: Movie.all
	end
	
	def show
		id = params[:id]
		if Song.exists?(id)
			@song = Song.find(id)
		else 
			render html: 'Song does not exist'
		end
	end
	
	def new
	
	end
	
	def create
		p = params.require(:song).permit(:title,:artist,:album,:genre,:release_date)
		#title = params[:movie].require(:title)
		#rating = params[:movie][:rating]
		#release_date = params[:movie].[:release_date]
		Song.create(p)
		#render json: params[:movie]
		redirect_to songs_path
	end
	
	def destroy
		Song.find(params[:id]).destroy
		#id = params[:id]
		#if Movie.exists?(id)
		#	Movie.find(id).destroy
		#else 
		#	render html: 'Movie does not exist'
		#end
		#render json: 'Movie numero '+id+' distrutto'
		redirect_to songs_path
	end
	
	def edit
		@song = Song.find(params[:id])
	end
	
	def update
		Song.find(params[:id]).update(params[:song].permit(:title,:artist,:album,:genre,:release_date))
		redirect_to songs_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canzones_helper.rb
module CanzonesHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songgoers_helper.rb
module SonggoersHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/canzones/create.html.erb
<h1>Canzones#create</h1>
<p>Find me in app/views/canzones/create.html.erb</p>

app/views/canzones/destroy.html.erb
<h1>Canzones#destroy</h1>
<p>Find me in app/views/canzones/destroy.html.erb</p>

app/views/canzones/new.html.haml
%h2 Testo canzone

= form_tag song_canzones_path, :method => :post do

 =label :canzone, :testos,'Song Lyrics'
 =text_area :canzone, :testos
 
 <br/><br/>
 = submit_tag 'Add lyric'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labassi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">   
 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songgoers/show.html.haml
%h2 Login
= form_tag login_path, :method => :post do
 
 = text_field :user, :name
 = label :user, :name,'Name'

 %br
 = password_field :user, :password
 = label :user, :password,'Password'

 %br
 
 = submit_tag 'Submit'
 
- if flash[:loginerror] 
 = 'User name or password is incorrect'

app/views/songs/_song_form.html.haml
= label :song, :title, 'Title'
= text_field :song, :title

= label :song, :artist, 'Artist'
= text_field :song, :artist

= label :song, :album, 'Album'
= text_field :song, :album

= label :song, :genre, 'Genre'
= text_field :song, :genre
	
= label :song, :release_date, 'Released on'
= date_select :song, :release_date

app/views/songs/edit.html.haml
%h2 Edit Song

= form_tag song_path(@song), :method => :put do

  = render :partial => 'song_form'
  
  = submit_tag 'Save Changes'

app/views/songs/index.html.haml
%h1 All songs for user #{session[:user]}

%table#songs
 %thead
  %tr
   %th Song Title
   %th Artist
   %th Album
   %th Genre
   %th Release Date
   %th More info
 %tbody
  -@all.each do |song|
   %tr
    %td= song.title
    %td= song.artist
    %td= song.album
    %td= song.genre
    %td= song.release_date
    %td= link_to "Details", song_path(song)

 #{link_to 'Add new song', new_song_path}
 %br
 %br
 = form_tag logout_path, :method => :post do
  = submit_tag 'Logout'

app/views/songs/new.html.haml
%h1 Create a new song

= form_tag songs_path , :method => :post do
	= render :partial => 'song_form'
	= submit_tag 'Save Changes'

app/views/songs/show.html.haml
%h1 Details about the song #{@song.title}

%ul#details
	%li
		Artist:
		= @song.artist
	%li
		Album:
		= @song.album
	%li
		Genre:
		= @song.genre
	%li
		Release date:
		= @song.release_date
		
%h3 Lyrics:

- if @song.canzones.empty?
	%p
		No lyrics for this song
- else
	%p
		- @song.canzones.each do |r|
			= r.testos
			%br
      
#{link_to 'Back to song list',songs_path}
%br
#{link_to 'Delete',song_path(@song), :method => :delete}
#{link_to 'Edit Info',edit_song_path(@song)}

%br
#{link_to 'Add lyrics',new_song_canzones_path(@song)}